---
- name: Perform Checks to make sure this Playbook will complete successfully
  hosts: localhost
  connection: local
  become: false
  gather_facts: true
  tasks:
    - name: run pre-check role to make sure workshop will complete provisioning
      include_role:
        name: workshop_check_setup

    - name: run AWS check setup if using AWS
      include_role:
        name: aws_check_setup

- name: Create lab instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false
  roles:
    - manage_ec2_instances

- name: wait for all nodes to have SSH reachability
  hosts: "managed_nodes:control_nodes:attendance"
  become: true
  gather_facts: false
  roles:
    - connectivity_test

#- name: Configure nginx on attendance host
#  hosts: attendance
#  become: true
#  gather_facts: true
#  tasks:
#    - block:
#        - include_role:
#           name: workshop_attendance_nginx
#       - include_role:
#            name: workshop_attendance
#      when: attendance|bool

- name: wait for all security nodes to have SSH reachability
  hosts: "security_connection_check"
  become: true
  gather_facts: false
  roles:
    - connectivity_test

- name: Configure common options on managed nodes and control nodes
  hosts: "managed_nodes:control_nodes"
  gather_facts: false
  become: true
  roles:
    - user_accounts
    - common


- name: print out information AWS instances provisioned
  hosts: localhost
  connection: local
  become:
  gather_facts: false
  tasks:
    - name: set facts for output
      set_fact:
        summary_information: |
          PROVISIONER SUMMARY
          *******************
          - Workshop name is {{ec2_name_prefix}}
          - Instructor inventory is located at  {{playbook_dir}}/{{ec2_name_prefix}}/instructor_inventory.txt
          - Private key is located at {{playbook_dir}}/{{ec2_name_prefix}}/{{ec2_name_prefix}}-private.pem
          - {{website_information}}
          - {{hostvars['attendance-host'].login_website_information | default("attendance feature is off") }}

          FAILURES
          *******************
          {{dns_information}}
          {{callback_information}}

    - name: Print Summary Information
      debug:
        msg: "{{summary_information}}"
